name: Build book
on: [push]
jobs:
  pdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: PDF
        uses: Glatek/pdflatex-action@main
        with:
          args: '-enable-write18 main.tex'
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: main.pdf
  epub:
    name: Build ePUB
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: ePUB
        uses: Glatek/pandoc-action@main
        with:
          args: '-f latex main.tex -o main.epub'
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ePUB
          path: main.epub
